<a href="https://colab.research.google.com/github/manjuvnair16/fcc-Data-Analysis-with-Python/blob/main/Intro-to-NumPy/NumpyExercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.19.5



![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Creation

### **Create a numpy array of size 10, filled with zeros.**

In [ ]:
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

###**Create a numpy array with values ranging from 10 to 49**

In [ ]:
 np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### **Create a numpy matrix of 2*2 integers, filled with ones.**

In [ ]:
np.ones([2,2], dtype=np.int)

array([[1, 1],
       [1, 1]])

### **Create a numpy matrix of 3*2 float numbers, filled with ones.**

In [ ]:
np.ones([3,2],dtype=np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### **Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.**

In [ ]:
X = np.arange(4, dtype=np.int)


In [ ]:
X

array([0, 1, 2, 3])

In [ ]:
np.ones_like(X)

array([1, 1, 1, 1])

### **Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.**

In [ ]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

In [ ]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

### **Create a numpy matrix of 4*4 integers, filled with fives.**

In [ ]:
np.ones([4,4],dtype=np.int)* 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### **Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.**

In [ ]:
X = np.array([[2,3],[6,2]],dtype=np.int)

In [ ]:
X

array([[2, 3],
       [6, 2]])

In [ ]:
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

### **Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.**

In [ ]:
np.identity(3,dtype=np.int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Create a numpy array, filled with 3 random integer values between 1 and 10.**

In [ ]:
np.random.randint(10, size=3)

array([1, 6, 7])

### **Create a 3\*3\*3 numpy matrix, filled with random float values.**

In [ ]:
np.random.random((3,3,3))

array([[[0.77816065, 0.39676549, 0.4979198 ],
        [0.65181979, 0.35239082, 0.12822067],
        [0.92109853, 0.56592627, 0.87306983]],

       [[0.12226835, 0.37371023, 0.21486218],
        [0.84459493, 0.02749274, 0.19232218],
        [0.7486585 , 0.78613566, 0.72296729]],

       [[0.06258759, 0.24997147, 0.56801871],
        [0.79090943, 0.51011734, 0.19903736],
        [0.81843114, 0.94004281, 0.40733426]]])

In [ ]:
np.random.randn(3,3,3)

array([[[ 1.79316077,  1.31260486,  2.05726304],
        [-0.19517527,  0.59610503,  1.8682225 ],
        [-0.23254208, -0.23589895,  0.26739946]],

       [[-0.03891477, -0.18615972,  0.45444203],
        [-0.75271776,  0.90793448,  1.19583227],
        [-0.97283743, -1.4440689 ,  0.76300288]],

       [[ 0.50108582, -1.10052777, -1.08011657],
        [-1.13674077, -0.30010354, -2.04344292],
        [-0.53420284, -0.64324844,  1.18438253]]])

### **Given the X python list convert it to an Y numpy array**

In [ ]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


### **Given the X numpy array, make a copy and store it on Y.**

In [ ]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 140429701305248
[5 2 3] 140429701305888


### **Create a numpy array with numbers from 1 to 10**

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### **Create a numpy array with the odd numbers between 1 to 10**

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

### **Create a numpy array with numbers from 1 to 10, in descending order**

In [ ]:
np.arange(1,11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### **Create a 3*3 numpy matrix, filled with values ranging from 0 to 8**

In [ ]:
np.arange(9).reshape([3,3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### **Show the memory size of the given Z numpy matrix**

In [ ]:
Z = np.ones((10,10),dtype=np.float) * 100
Z

array([[100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100., 100., 100., 100., 100., 100.]])

In [ ]:
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# **Array indexation**

### **Given the X numpy array, show it's first element**

In [ ]:
X = np.array(['A','B','C','D','E'])
X[0]

'A'

### **Given the X numpy array, show it's last element**

In [ ]:
X[-1]
X[len(X)-1]

'E'

### **Given the X numpy array, show it's first three elements**

In [ ]:
X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

### **Given the X numpy array, show all middle elements**

In [ ]:
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

### **Given the X numpy array, show the elements in reverse position**

In [ ]:
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

### **Given the X numpy array, show the elements in an odd position**

In [ ]:
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [ ]:
X[[0,2,-1]]

array(['A', 'C', 'E'], dtype='<U1')

### **Given the X numpy matrix, show the first row elements**

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

### **Given the X numpy matrix, show the last row elements**

In [ ]:
X[-1]

array([13, 14, 15, 16])

### **Given the X numpy matrix, show the first element on first row**

In [ ]:
X[0,0]

1

### **Given the X numpy matrix, show the last element on last row**

In [ ]:
X[-1,-1]

16

### **Given the X numpy matrix, show the middle row elements**

In [ ]:
X[1:-1, :]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### **Given the X numpy matrix, show the first two elements on the first two rows**

In [ ]:
#X[0:2,0:2]
X[:2,:2]

array([[1, 2],
       [5, 6]])

### **Given the X numpy matrix, show the last two elements on the last two rows**

In [ ]:
X[-2: ,-2:]

array([[11, 12],
       [15, 16]])

# **Array manipulation**

### **Convert the given integer numpy array to float**

In [ ]:

X = [-5, -3, 0, 10, 40]
np.array(X, dtype=np.float)

array([-5., -3.,  0., 10., 40.])

### **Reverse the given numpy array (first element becomes last)**

In [ ]:
A = X[::-1]
A

[40, 10, 0, -3, -5]

### **Order (sort) the given numpy array**

In [ ]:
X = [0, 10, -5, 40, -3]
X.sort()
X

[-5, -3, 0, 10, 40]

### **Given the X numpy array, set the fifth element equal to 1**

In [ ]:
X[4] = 1
X

[-5, -3, 0, 10, 1]

### **Given the X numpy array, change the 50 with a 40**

In [ ]:

X = np.array([10, 20, 30, 50])
X[-1] =40
X

array([10, 20, 30, 40])

### **Given the X numpy matrix, change the last row with all 1**

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] =1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

### **Given the X numpy matrix, change the last item on the last row with a 0**

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

### **Given the X numpy matrix, add 5 to every element**

In [ ]:
X = np.arange(1,17).reshape(4,4)
X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

# **Boolean arrays (also called masks)**

### **Given the X numpy array, make a mask showing negative elements**

In [ ]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X
mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

### **Given the X numpy array, get the negative elements**

In [ ]:
X[mask]

array([-1,  0, -4,  0,  0, -9])

### **Given the X numpy array, get numbers higher than 5**

In [ ]:
mask = X > 5
X[mask]

array([ 6, 10])

### **Given the X numpy array, get numbers higher than the elements mean**

In [ ]:
mean = X.mean()
mask = X > mean
X[mask]

array([ 2,  5,  6, 10])

### **Given the X numpy array, get numbers equal to 2 or 10**

In [ ]:
mask = (X ==2)| (X == 10)
X[mask]

array([ 2, 10])

# **Logic functions**

### **Given the X numpy array, return True if none of its elements is zero**

In [ ]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()

False

### ** Given the X numpy array, return True if any of its elements is zero**

In [ ]:
X.any()

True

# **Summary statistics**

### **Given the X numpy array, show the sum of its elements**

In [ ]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
#X.sum()
np.sum(X)

43

### **Given the X numpy array, show the mean value of its elements**

In [ ]:
X.mean()

4.777777777777778

###**Given the X numpy matrix, show the sum of its columns**

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.sum(axis=0)

array([28, 32, 36, 40])

### **Given the X numpy matrix, show the mean value of its rows**

In [ ]:
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

### **Given the X numpy array, show the max value of its elements**

In [ ]:
X.max()

16