<a href="https://colab.research.google.com/github/manjuvnair16/fcc-Data-Analysis-with-Python/blob/main/Intro-to-NumPy/NumpyLesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sys

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
b = np.array([0,.5,1,1.5,2])

In [ ]:
a[0],a[1]

(1, 2)

In [ ]:
a[0:]

array([1, 2, 3, 4])

In [ ]:
a[1:-1]

array([2, 3])

In [ ]:
a[::3]

array([1, 4])

In [ ]:
b[0], b[1], b[3]

(0.0, 0.5, 1.5)

In [ ]:
b[[0,1,3]]


array([0. , 0.5, 1.5])

# Array Types

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
c = np.array(['a','b','c','d'])

In [ ]:
c.dtype

dtype('<U1')

In [ ]:
d = np.array([{'a': 'value'},{'b' :'value2'}])

In [ ]:
d.dtype

dtype('O')

# Array Dimensions & Shape

In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6]
            ])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

In [ ]:
B = np.array([
              [
               [1,2,3],
               [4,5,6],
               [7,8,9],
               [4,5,6]
              ],
              [
               [3,4,5],
               [7,8,9],
               [10,11,12],
               [7,8,9]
              ]
            ])

In [ ]:
B.shape

(2, 4, 3)

In [ ]:
B.size

24

In [ ]:
B.ndim

3

In [ ]:
C = np.array([
              [
               [1,2,3],
               [4,5,6]
              ],
              [
               [7,8,9]
              ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [ ]:
C.shape

(2,)

In [ ]:
C.size

2

In [ ]:
C.ndim

1

***

---


# Indexing & Slicing of Matrix

In [ ]:
A =np.array([
             [1,2,3],
             [4,5,6],
             [7,8,9]
          ])

In [ ]:
A[1]

array([4, 5, 6])

In [ ]:
A[1][0]

4

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
A[ : , :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
A[ :2, 2: ]

array([[3],
       [6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A[1] = np.array([10,10,10])

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
A[2] = 706

In [ ]:
A

array([[  1,   2,   3],
       [ 10,  10,  10],
       [706, 706, 706]])

***

---


# Statistics

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a.sum()

10

In [ ]:
a.mean()

2.5

In [ ]:
a.std()

1.118033988749895

In [ ]:
a.var()

1.25

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

45

In [ ]:
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
A.mean()

5.0

In [ ]:
A.var()

6.666666666666667

In [ ]:
A.std()

2.581988897471611

In [ ]:
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.var(axis=0)

array([6., 6., 6.])

In [ ]:
x = np.array([
              [
                [ 0,  1,  2],
                [ 3,  4,  5],
                [ 6,  7,  8]
              ],
              [
               [ 9, 10, 11],
               [12, 13, 14],
               [15, 16, 17]
              ],
              [
               [18, 19, 20],
               [21, 22, 23],
               [24, 25, 26]
              ]
            ])

In [ ]:
x.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [ ]:
x.sum(axis=1)

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

In [ ]:
x.sum(axis=2)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])




---

#Broadcasting & Vectorized Operations

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a+10

array([10, 11, 12, 13])

In [ ]:
a*10

array([ 0, 10, 20, 30])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a+=10

In [ ]:
a

array([10, 11, 12, 13])

In [ ]:
a= np.arange(4)

In [ ]:
l = [0,1,2,3]

In [ ]:
[item + 10 for item in l]

[10, 11, 12, 13]

In [ ]:
b = np.array([10,10,10,10])

In [ ]:
b

array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

# **Boolean arrays**
(Also called masks)

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a[0] ,a[-1]

(0, 3)

In [ ]:
a[[0,-1]]

array([0, 3])

In [ ]:
a[[True, False, False, True]]


array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:

a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~ (a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:

a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size=(3, 3))
A

array([[63, 68,  1],
       [89, 35, 86],
       [26,  7, 74]])

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([63,  1, 35, 26, 74])

In [ ]:
A > 30

array([[ True,  True, False],
       [ True,  True,  True],
       [False, False,  True]])

In [ ]:
A[ A > 30]

array([63, 68, 89, 35, 86, 74])

# **Linear Algebra**

In [ ]:
A = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
            ])

In [ ]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
np.matmul(A,B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# **Size of objects in Memory**

**Int, floats**

In [ ]:
import sys
sys.getsizeof(1)  # An integer in Python is > 24bytes

28

In [ ]:
sys.getsizeof(10**100) # Longs are even larger

72

In [ ]:
import numpy as np
a = np.arange(1)
a
np.dtype(int).itemsize  # Numpy size for int64 is much smaller (8)
a.itemsize

8

In [ ]:
np.dtype(np.int8).itemsize # Numpy size for int8 is smaller than int64

1

In [ ]:
np.dtype(float).itemsize

8

**Lists are even larger**

In [ ]:
sys.getsizeof([1]) # A one-element list

80

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

8

**And performance is also important**

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 0 ns, sys: 565 µs, total: 565 µs
Wall time: 980 µs


333328333350000

In [ ]:
%time sum([item** 2 for item in l])

CPU times: user 28.6 ms, sys: 6.22 ms, total: 34.8 ms
Wall time: 36.9 ms


333328333350000

# **Useful Numpy functions**
**random**

In [ ]:
np.random.random(size=2)

array([0.20540462, 0.09814281])

In [ ]:
np.random.normal(size=10)

array([-1.32715185, -0.28945982,  0.47412079,  0.95501912, -0.0331201 ,
       -0.55800205,  1.45977601, -0.95606367,  0.59780993, -0.15454125])

In [ ]:
np.random.rand(2,4)

array([[0.5171091 , 0.8044171 , 0.97541136, 0.58051645],
       [0.90128448, 0.5925179 , 0.38940497, 0.35257888]])

**arange**

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.arange(1,4)

array([1, 2, 3])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

**reshape**

In [ ]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.arange(3,15).reshape(4,3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

**linspace**

In [ ]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [ ]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
np.linspace(0,10,20,False) # False implies that the stop number (10) won't be included in the result array, default is True

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

**zeros, ones, empty**

In [ ]:
np.zeros(3, dtype=np.int)

array([0, 0, 0])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,3), dtype=np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(2)

array([1., 1.])

In [ ]:
np.ones((2,3), dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.empty(3)

array([1., 3., 5.])

In [ ]:
np.empty((2,3))

array([[4.64798384e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

**identity and eye**

In [ ]:
np.identity(3,dtype=np.int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8,4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World"[-1]

'd'